### ISSUE TITLE
Only register collectors if the endpoint supports it.

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/sap_host_exporter#22]
Right now, we register all the collectors, regardless of what is available on the SAPControl endpoint.

Some collector may not be necessarily relevant for every SAP host, so we need to perform some kind of preflight check, possibly using the `GetProcessList` web service method, to asses whether or not a collector should be registered.

One example is avoiding registering the EnqueueServer collector if the host doesn't run the EnqueueServer process.

**Comment by stefanotorresi** [comment]
So, apparently we really need this, because lingering collectors querying for non-relevant data for an instance will cause some SAPControl methods to make the entire sapstartsvc malfunction. (see #31)

Here is a possible way to go with this:
- extract the registration of the two optional collectors, Enqueue Server Collector and Dispatcher Collector, from main into a separate function inside the `collector` package. (the Start Service collector can always be registered because any type of instance will support the web service methods used in it)
- within this new function, let's call it `registerOptionalCollectors` for now, we query SAPControl webservice with the `GetProcessList` method.
- we look up for each process `name` field. We are currently interested in `msg_server` and `disp+work` processes. If any of these is present, we register respectively the Enqueue Server Collector and the Dispatcher Collector.
- after this optional registration happens, the `main` continues in starting the exporter.

Any existing error handling should be handled so that the main receive the errors and bails out if anything goes wrong. We no longer work under the assumption that the system is tolerant to collector registration failures, as done so far.
To avoid further issues with the SAP cluster, failure to start a collector now becomes a roadblock for the startup of the whole exporter. This way we can take advantage of the inherent `up` status that a running exporter implies, i.e. if the exporter is down, the SAP instance might be broken.

**Comment by MalloZup** [comment]
closing pr merged
