### ISSUE TITLE
HTTP Error : Unauthorized

### ISSUE THREAD

**Issue by pipinstallyogi** [SUSE/sap_host_exporter#49]
Hello everyone,

With every scrape from Prometheus (i.e. at every 1 minute interval), the following Warning/Error comes at the terminal where sap_host_exporter is running:

WARN[1754] Dispatcher Collector scrape failed: SAPControl web service error: HTTP Error: 'Unauthorized'

Any inputs how to get through this?
Thanks

**Comment by stefanotorresi** [comment]
@pipinstallyogi did you take a look at the the [configuration](https://github.com/SUSE/sap_host_exporter#configuration) instructions? The example config explains how to configure HTTP authentication with SAPControl.

**Comment by pipinstallyogi** [comment]
Hi,
As the Configuration section tells that the configuration file is optional. So, I haven't tried anything related to configuration file. If you suggest that, I will try adding the configuration file and observe the outcome. I will then update here.
Thanks

**Comment by pipinstallyogi** [comment]
Ok, so as i configured the sap_host_exporter.yaml file the error seems to be gone. The one thing to take care is making an entry for sap-control-user and sap-control-password.  These provides the Basic HTTP Authentication credentials for the SAPControl web service, e.g. <sid>adm user and password. I think the issue is solved.
Thanks
